deploy:
  provider: pages
  local_dir: _site
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: source

script:
    - JEKYLL_ENV=production bundle exec jekyll build 
    - echo 'http://intelligentthingsfund.com' > _site/CNAME
    - ls -latr
    - ls -latr _site
    - cat _site/index.html

notifications:
  email: 
    on_success: never
    on_failure: always
